services:
    outline-admin:
        image: amro045/outline-admin:latest
        container_name: outline-admin
        ports:
            - "3000:3000"
        volumes:
            - "~/.outline-admin-data:/app/data"
        networks:
            - outline_admin
        restart: unless-stopped

networks:
    outline_admin:
        driver: bridge
